# Generated by Django 5.1.1 on 2024-09-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('image_src', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('discover_date', models.DateTimeField(auto_now_add=True, verbose_name='datetime of the discovery')),
                ('types', models.ManyToManyField(to='pokedex.type')),
            ],
        ),
    ]
